 name: Python application

 on:
   push:
     branches: [ main ]

 jobs:
   build:

     runs-on: windows-2022

     steps:
     - uses: actions/checkout@v2
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         if ( -f requirements.txt ; then pip install -r requirements.txt; fi)
     - name: Test selenium
       run: |
         python manage.py test
